<?php

namespace App\Domain\Entities;

use App\Domain\VOs\MoneyVO;

class TransactionEntity
{
    public function __construct(
        public readonly string $transactionUuid,
        public readonly string $transactionType, //TODO ENUM TransactionType PURCHASE, WITHDRAWAL, DEPOSIT, TRANSFER, PAYMENT
        public readonly string $cardUuid,
        public readonly ?string $uuid,
        public readonly ?int $id,
        // Request Fields - ISO8583
        public readonly ?string $requestMti,
        public readonly ?string $requestCardNumber,
        public readonly ?string $requestProcessingCode,
        public readonly ?int $requestTransactionAmountLocalOriginal,
        public readonly ?MoneyVO $requestTransactionAmountLocal,
        public readonly ?MoneyVO $requestTransactionAmountReferencia,
        public readonly ?MoneyVO $requestAmountInCardHolderBilling,
        public readonly ?string $requestTransmitionDateAndTime,
        public readonly ?string $requestConvertionRateCardHolderBilling,
        public readonly ?string $requestSystemTraceAuditNumber,
        public readonly ?string $requestLocalTransactionTime,
        public readonly ?string $requestLocalTransactionDate,
        public readonly ?string $requestExpirationDate,
        public readonly ?string $requestMcc,
        public readonly ?string $requestAcquiringInstitutionCountryCode,
        public readonly ?string $requestPosEntryMode,
        public readonly ?string $requestPosConditionCode,
        public readonly ?string $requestAquiringInstitutionCode,
        public readonly ?string $requestRetrievalReferenceNumber,
        public readonly ?string $requestAuthorizationResponseCode,
        public readonly ?string $requestCardAcceptorTerminal,
        public readonly ?string $requestCardAcceptorIdentificationCode,
        public readonly ?string $requestCardAcceptorNameLocation,
        public readonly ?string $requestContainsPdsInLtvFormat,
        public readonly ?string $requestTransactionCurrencyCode,
        public readonly ?string $requestTransactionAmount,
        public readonly ?string $requestCurrencyCodeCardholderBilling,
        public readonly ?string $requestPsProductCode,
        // Response Fields
        public readonly ?string $responseMti,
        public readonly ?string $responseCardNumber,
        public readonly ?string $responseProcessingCode,
        public readonly ?MoneyVO $responseTransactionAmountLocal,
        public readonly ?MoneyVO $responseAmountInCardHolderBilling,
        public readonly ?string $responseTransmitionDateAndTime,
        public readonly ?string $responseConversionRate,
        public readonly ?string $responseSystemTraceAuditNumber,
        public readonly ?string $responseAcquiringInstitutionCountryCode,
        public readonly ?string $responsePosConditionCode,
        public readonly ?string $responseAquiringInstitutionCode,
        public readonly ?string $responseRetrievalReferenceNumber,
        public readonly ?string $responseAuthorizationIdentificationResponse,
        public readonly ?string $responseCode,
        public readonly ?string $responseCardAcceptorTerminal,
        public readonly ?string $responseCardAcceptorIdentificationCode,
        public readonly ?string $responseCardAcceptorNameLocation,
        public readonly ?string $responseTransactionCurrencyCode,
        public readonly ?string $responseCurrencyCodeCardholderBilling,
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            transactionUuid: $data['transaction_uuid'],
            transactionType: $data['transaction_type'], 
            cardUuid: $data['card_uuid'],
            uuid: $data['uuid'] ?? null,
            id: $data['id'] ?? null,
            requestMti: $data['request_mti'] ?? null,
            requestCardNumber: $data['request_card_number'] ?? null,
            requestProcessingCode: $data['request_processing_code'] ?? null,
            requestTransactionAmountLocalOriginal: $data['request_transaction_amount_local_original'] ?? null,
            requestTransactionAmountLocal: isset($data['request_transaction_amount_local']) ? MoneyVO::fromCents($data['request_transaction_amount_local']) : null,
            requestTransactionAmountReferencia: isset($data['request_transaction_amount_referencia']) ? MoneyVO::fromCents($data['request_transaction_amount_referencia']) : null,
            requestAmountInCardHolderBilling: isset($data['request_amount_in_card_holder_billing']) ? MoneyVO::fromCents($data['request_amount_in_card_holder_billing']) : null,
            requestTransmitionDateAndTime: $data['request_transmition_date_and_time'] ?? null,
            requestConvertionRateCardHolderBilling: $data['request_convertion_rate_card_holder_billing'] ?? null,
            requestSystemTraceAuditNumber: $data['request_system_trace_audit_number'] ?? null,
            requestLocalTransactionTime: $data['request_local_transaction_time'] ?? null,
            requestLocalTransactionDate: $data['request_local_transaction_date'] ?? null,
            requestExpirationDate: $data['request_expiration_date'] ?? null,
            requestMcc: $data['request_mcc'] ?? null,
            requestAcquiringInstitutionCountryCode: $data['request_acquiring_institution_country_code'] ?? null,
            requestPosEntryMode: $data['request_pos_entry_mode'] ?? null,
            requestPosConditionCode: $data['request_pos_condition_code'] ?? null,  
            requestAquiringInstitutionCode: $data['request_aquiring_institution_code'] ?? null,     
            requestRetrievalReferenceNumber: $data['request_retrieval_reference_number'] ?? null,
            requestAuthorizationResponseCode: $data['request_authorization_response_code'] ?? null,
            requestCardAcceptorTerminal: $data['request_card_acceptor_terminal'] ?? null,
            requestCardAcceptorIdentificationCode: $data['request_card_acceptor_identification_code'] ?? null,
            requestCardAcceptorNameLocation: $data['request_card_acceptor_name_location'] ?? null,
            requestContainsPdsInLtvFormat: $data['request_contains_pds_in_ltv_format'] ?? null,
            requestTransactionCurrencyCode: $data['request_transaction_currency_code'] ?? null,
            requestTransactionAmount: $data['request_transaction_amount'] ?? null,
            requestCurrencyCodeCardholderBilling: $data['request_currency_code_cardholder_billing'] ?? null,
            requestPsProductCode: $data['request_ps_product_code'] ?? null,
            responseMti: $data['response_mti'] ?? null,
            responseCardNumber: $data['response_card_number'] ?? null,
            responseProcessingCode: $data['response_processing_code'] ?? null,
            responseTransactionAmountLocal: isset($data['response_transaction_amount_local']) ? MoneyVO::fromCents($data['response_transaction_amount_local']) : null,
            responseAmountInCardHolderBilling: isset($data['response_amount_in_card_holder_billing']) ? MoneyVO::fromCents($data['response_amount_in_card_holder_billing']) : null,
            responseTransmitionDateAndTime: $data['response_transmition_date_and_time'] ?? null,
            responseConversionRate: $data['response_conversion_rate'] ?? null,
            responseSystemTraceAuditNumber: $data['response_system_trace_audit_number'] ?? null,
            responseAcquiringInstitutionCountryCode: $data['response_acquiring_institution_country_code'] ?? null,
            responsePosConditionCode: $data['response_pos_condition_code'] ?? null,
            responseAquiringInstitutionCode: $data['response_aquiring_institution_code'] ?? null,
            responseRetrievalReferenceNumber: $data['response_retrieval_reference_number'] ?? null,
            responseAuthorizationIdentificationResponse: $data['response_authorization_identification_response'] ?? null,
            responseCode: $data['response_code'] ?? null,
            responseCardAcceptorTerminal: $data['response_card_acceptor_terminal'] ?? null,
            responseCardAcceptorIdentificationCode: $data['response_card_acceptor_identification_code'] ?? null,
            responseCardAcceptorNameLocation: $data['response_card_acceptor_name_location'] ?? null,
            responseTransactionCurrencyCode: $data['response_transaction_currency_code'] ?? null,
            responseCurrencyCodeCardholderBilling: $data['response_currency_code_cardholder_billing'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'transaction_uuid' => $this->transactionUuid,
            'transaction_type' => $this->transactionType,
            'card_uuid' => $this->cardUuid,
            'uuid' => $this->uuid,
            'id' => $this->id,
            'request_mti' => $this->requestMti,
            'request_card_number' => $this->requestCardNumber,
            'request_processing_code' => $this->requestProcessingCode,
            'request_transaction_amount_local_original' => $this->requestTransactionAmountLocalOriginal,
            'request_transaction_amount_local' => isset($this->requestTransactionAmountLocal) ? $this->requestTransactionAmountLocal->toCents() : null,
            'request_transaction_amount_referencia' => isset($this->requestTransactionAmountReferencia) ? $this->requestTransactionAmountReferencia->toCents() : null,
            'request_amount_in_card_holder_billing' => isset($this->requestAmountInCardHolderBilling) ? $this->requestAmountInCardHolderBilling->toCents() : null,
            'request_transmition_date_and_time' => $this->requestTransmitionDateAndTime,
            'request_convertion_rate_card_holder_billing' => $this->requestConvertionRateCardHolderBilling,
            'request_system_trace_audit_number' => $this->requestSystemTraceAuditNumber,
            'request_local_transaction_time' => $this->requestLocalTransactionTime,
            'request_local_transaction_date' => $this->requestLocalTransactionDate,
            'request_expiration_date' => $this->requestExpirationDate,
            'request_mcc' => $this->requestMcc,
            'request_acquiring_institution_country_code' => $this->requestAcquiringInstitutionCountryCode,
            'request_pos_entry_mode' => $this->requestPosEntryMode,
            'request_pos_condition_code' => $this->requestPosConditionCode,
            'request_aquiring_institution_code' => $this->requestAquiringInstitutionCode,
            'request_retrieval_reference_number' => $this->requestRetrievalReferenceNumber, 
            'request_authorization_response_code' => $this->requestAuthorizationResponseCode,
            'request_card_acceptor_terminal' => $this->requestCardAcceptorTerminal,
            'request_card_acceptor_identification_code' => $this->requestCardAcceptorIdentificationCode,
            'request_card_acceptor_name_location' => $this->requestCardAcceptorNameLocation,
            'request_contains_pds_in_ltv_format' => $this->requestContainsPdsInLtvFormat,
            'request_transaction_currency_code' => $this->requestTransactionCurrencyCode,
            'request_transaction_amount' => $this->requestTransactionAmount,
            'request_currency_code_cardholder_billing' => $this->requestCurrencyCodeCardholderBilling,
            'request_ps_product_code' => $this->requestPsProductCode,
            'response_mti' => $this->responseMti,
            'response_card_number' => $this->responseCardNumber,
            'response_processing_code' => $this->responseProcessingCode,
            'response_transaction_amount_local' => isset($this->responseTransactionAmountLocal) ? $this->responseTransactionAmountLocal->toCents() : null,
            'response_amount_in_card_holder_billing' => isset($this->responseAmountInCardHolderBilling) ? $this->responseAmountInCardHolderBilling->toCents() : null,
            'response_transmition_date_and_time' => $this->responseTransmitionDateAndTime,
            'response_conversion_rate' => $this->responseConversionRate,
            'response_system_trace_audit_number' => $this->responseSystemTraceAuditNumber,
            'response_acquiring_institution_country_code' => $this->responseAcquiringInstitutionCountryCode,
            'response_pos_condition_code' => $this->responsePosConditionCode,
            'response_aquiring_institution_code' => $this->responseAquiringInstitutionCode,
            'response_retrieval_reference_number' => $this->responseRetrievalReferenceNumber,
            'response_authorization_identification_response' => $this->responseAuthorizationIdentificationResponse,
            'response_code' => $this->responseCode,
            'response_card_acceptor_terminal' => $this->responseCardAcceptorTerminal,
            'response_card_acceptor_identification_code' => $this->responseCardAcceptorIdentificationCode,
            'response_card_acceptor_name_location' => $this->responseCardAcceptorNameLocation,
            'response_transaction_currency_code' => $this->responseTransactionCurrencyCode,
            'response_currency_code_cardholder_billing' => $this->responseCurrencyCodeCardholderBilling,
        ];
    }
    
    public static function fromModel(\App\Models\TransactionModel $model): self
    {
        return new self(
            transactionUuid: $model->transaction_uuid,
            transactionType: $model->transaction_type,
            cardUuid: $model->card_uuid,
            uuid: $model->uuid,
            id: $model->id,
            requestMti: $model->request_mti,
            requestCardNumber: $model->request_card_number,
            requestProcessingCode: $model->request_processing_code,
            requestTransactionAmountLocalOriginal: $model->request_transaction_amount_local_original,
            requestTransactionAmountLocal: isset($model->request_transaction_amount_local) ? MoneyVO::fromCents($model->request_transaction_amount_local) : null,
            requestTransactionAmountReferencia: isset($model->request_transaction_amount_referencia) ? MoneyVO::fromCents($model->request_transaction_amount_referencia) : null,
            requestAmountInCardHolderBilling: isset($model->request_amount_in_card_holder_billing) ? MoneyVO::fromCents($model->request_amount_in_card_holder_billing) : null,
            requestTransmitionDateAndTime: $model->request_transmition_date_and_time,
            requestConvertionRateCardHolderBilling: $model->request_convertion_rate_card_holder_billing,
            requestSystemTraceAuditNumber: $model->request_system_trace_audit_number,
            requestLocalTransactionTime: $model->request_local_transaction_time,
            requestLocalTransactionDate: $model->request_local_transaction_date,
            requestExpirationDate: $model->request_expiration_date,
            requestMcc: $model->request_mcc,
            requestAcquiringInstitutionCountryCode: $model->request_acquiring_institution_country_code,
            requestPosEntryMode: $model->request_pos_entry_mode,
            requestPosConditionCode: $model->request_pos_condition_code,  
            requestAquiringInstitutionCode: $model->request_aquiring_institution_code,     
            requestRetrievalReferenceNumber: $model->request_retrieval_reference_number,
            requestAuthorizationResponseCode: $model->request_authorization_response_code,
            requestCardAcceptorTerminal: $model->request_card_acceptor_terminal,
            requestCardAcceptorIdentificationCode: $model->request_card_acceptor_identification_code,
            requestCardAcceptorNameLocation: $model->request_card_acceptor_name_location,
            requestContainsPdsInLtvFormat: $model->request_contains_pds_in_ltv_format,
            requestTransactionCurrencyCode: $model->request_transaction_currency_code,
            requestTransactionAmount: $model->request_transaction_amount,
            requestCurrencyCodeCardholderBilling: $model->request_currency_code_cardholder_billing,
            requestPsProductCode: $model->request_ps_product_code,
            responseMti: $model->response_mti,
            responseCardNumber: $model->response_card_number,
            responseProcessingCode: $model->response_processing_code,
            responseTransactionAmountLocal: isset($model->response_transaction_amount_local) ? MoneyVO::fromCents($model->response_transaction_amount_local) : null,
            responseAmountInCardHolderBilling: isset($model->response_amount_in_card_holder_billing) ? MoneyVO::fromCents($model->response_amount_in_card_holder_billing) : null,
            responseTransmitionDateAndTime: $model->response_transmition_date_and_time,
            responseConversionRate: $model->response_conversion_rate,
            responseSystemTraceAuditNumber: $model->response_system_trace_audit_number,
            responseAcquiringInstitutionCountryCode: $model->response_acquiring_institution_country_code,
            responsePosConditionCode: $model->response_pos_condition_code,
            responseAquiringInstitutionCode: $model->response_aquiring_institution_code,
            responseRetrievalReferenceNumber: $model->response_retrieval_reference_number,
            responseAuthorizationIdentificationResponse: $model->response_authorization_identification_response,
            responseCode: $model->response_code,
            responseCardAcceptorTerminal: $model->response_card_acceptor_terminal,
            responseCardAcceptorIdentificationCode: $model->response_card_acceptor_identification_code,
            responseCardAcceptorNameLocation: $model->response_card_acceptor_name_location,
            responseTransactionCurrencyCode: $model->response_transaction_currency_code,
            responseCurrencyCodeCardholderBilling: $model->response_currency_code_cardholder_billing,
        );
    }

    public function isApproved(): bool
    {
        return $this->responseCode === '00';
    }

    public function isDeclined(): bool
    {
        return $this->responseCode !== '00';
    }

    public function exists(string $otherTransactionUuid): bool
    {
        return $this->transactionUuid === $otherTransactionUuid;
    }
    
}
